/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  DigitalTwinsAddHeaders,
  DigitalTwinsAddRelationshipHeaders,
  DigitalTwinsGetByIdHeaders,
  DigitalTwinsGetComponentHeaders,
  DigitalTwinsGetRelationshipByIdHeaders,
  DigitalTwinsUpdateComponentHeaders,
  DigitalTwinsUpdateHeaders,
  DigitalTwinsUpdateRelationshipHeaders,
  ErrorModel,
  ErrorResponse,
  IncomingRelationship,
  IncomingRelationshipCollection,
  InnerError,
  RelationshipCollection
} from "../models/mappers";
