// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AdtExplorer.Functions.Sdk
{
    using Microsoft.Rest;
    using Microsoft.Rest.Azure;
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for QueryOperations.
    /// </summary>
    public static partial class QueryOperationsExtensions
    {
            /// <summary>
            /// Executes a query that allows traversing relationships and filtering by
            /// property values.
            /// Status codes:
            /// 200 (OK): Success.
            /// 400 (Bad Request): The request is invalid.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='querySpecification'>
            /// The query specification to execute.
            /// </param>
            public static QueryResult QueryTwins(this IQueryOperations operations, QuerySpecification querySpecification)
            {
                return operations.QueryTwinsAsync(querySpecification).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Executes a query that allows traversing relationships and filtering by
            /// property values.
            /// Status codes:
            /// 200 (OK): Success.
            /// 400 (Bad Request): The request is invalid.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='querySpecification'>
            /// The query specification to execute.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<QueryResult> QueryTwinsAsync(this IQueryOperations operations, QuerySpecification querySpecification, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.QueryTwinsWithHttpMessagesAsync(querySpecification, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
