// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AdtExplorer.Functions.Sdk.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Error definition.
    /// </summary>
    public partial class Error
    {
        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        public Error()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Error class.
        /// </summary>
        /// <param name="code">Service specific error code which serves as the
        /// substatus for the HTTP error code.</param>
        /// <param name="message">A human-readable representation of the
        /// error.</param>
        /// <param name="details">Internal error details.</param>
        /// <param name="innererror">An object containing more specific
        /// information than the current object about the error.</param>
        public Error(string code = default(string), string message = default(string), IList<Error> details = default(IList<Error>), InnerError innererror = default(InnerError))
        {
            Code = code;
            Message = message;
            Details = details;
            Innererror = innererror;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets service specific error code which serves as the substatus for
        /// the HTTP error code.
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; private set; }

        /// <summary>
        /// Gets a human-readable representation of the error.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// Gets internal error details.
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IList<Error> Details { get; private set; }

        /// <summary>
        /// Gets or sets an object containing more specific information than
        /// the current object about the error.
        /// </summary>
        [JsonProperty(PropertyName = "innererror")]
        public InnerError Innererror { get; set; }

    }
}
