// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AdtExplorer.Functions.Sdk.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A model definition and metadata for that model.
    /// </summary>
    public partial class ModelData
    {
        /// <summary>
        /// Initializes a new instance of the ModelData class.
        /// </summary>
        public ModelData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelData class.
        /// </summary>
        /// <param name="id">The id of the model as specified in the model
        /// definition.</param>
        /// <param name="displayName">A language map that contains the
        /// localized display names as specified in the model
        /// definition.</param>
        /// <param name="description">A language map that contains the
        /// localized descriptions as specified in the model
        /// definition.</param>
        /// <param name="uploadTime">The time the model was uploaded to the
        /// service.</param>
        /// <param name="decommissioned">Indicates if the model is
        /// decommissioned. Decommissioned models cannot be referenced by newly
        /// created digital twins.</param>
        /// <param name="model">The model definition.</param>
        public ModelData(string id, object displayName = default(object), object description = default(object), System.DateTime? uploadTime = default(System.DateTime?), bool? decommissioned = default(bool?), object model = default(object))
        {
            DisplayName = displayName;
            Description = description;
            Id = id;
            UploadTime = uploadTime;
            Decommissioned = decommissioned;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a language map that contains the localized display
        /// names as specified in the model definition.
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public object DisplayName { get; set; }

        /// <summary>
        /// Gets or sets a language map that contains the localized
        /// descriptions as specified in the model definition.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public object Description { get; set; }

        /// <summary>
        /// Gets or sets the id of the model as specified in the model
        /// definition.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the time the model was uploaded to the service.
        /// </summary>
        [JsonProperty(PropertyName = "uploadTime")]
        public System.DateTime? UploadTime { get; set; }

        /// <summary>
        /// Gets or sets indicates if the model is decommissioned.
        /// Decommissioned models cannot be referenced by newly created digital
        /// twins.
        /// </summary>
        [JsonProperty(PropertyName = "decommissioned")]
        public bool? Decommissioned { get; set; }

        /// <summary>
        /// Gets or sets the model definition.
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public object Model { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
        }
    }
}
