// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AdtExplorer.Functions.Sdk.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A query specification containing either a query statement or a
    /// continuation token from a previous query result.
    /// </summary>
    public partial class QuerySpecification
    {
        /// <summary>
        /// Initializes a new instance of the QuerySpecification class.
        /// </summary>
        public QuerySpecification()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QuerySpecification class.
        /// </summary>
        /// <param name="query">The query to execute. This value is ignored if
        /// a continuation token is provided.</param>
        /// <param name="continuationToken">A token which is used to retrieve
        /// the next set of results from a previous query.</param>
        public QuerySpecification(string query = default(string), string continuationToken = default(string))
        {
            Query = query;
            ContinuationToken = continuationToken;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the query to execute. This value is ignored if a
        /// continuation token is provided.
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// Gets or sets a token which is used to retrieve the next set of
        /// results from a previous query.
        /// </summary>
        [JsonProperty(PropertyName = "continuationToken")]
        public string ContinuationToken { get; set; }

    }
}
