// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AdtExplorer.Functions.Sdk.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for QueryTwins operation.
    /// </summary>
    public partial class QueryQueryTwinsHeaders
    {
        /// <summary>
        /// Initializes a new instance of the QueryQueryTwinsHeaders class.
        /// </summary>
        public QueryQueryTwinsHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryQueryTwinsHeaders class.
        /// </summary>
        /// <param name="queryCharge">The query charge.</param>
        public QueryQueryTwinsHeaders(string queryCharge = default(string))
        {
            QueryCharge = queryCharge;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the query charge.
        /// </summary>
        [JsonProperty(PropertyName = "query-charge")]
        public string QueryCharge { get; set; }

    }
}
